### ISSUE TITLE
Could a license be added?

### ISSUE THREAD

**Issue by eeskildsen** [MarkPieszak/Angular1-ngForm-ngSubmit-fixes#8]
Could we add a license, e.g., MIT? I believe the current "default" is copyrighted, all rights reserved.

**Comment by MarkPieszak** [comment]
Sure let me get one in there! One second.

**Comment by eeskildsen** [comment]
Awesome, thanks! Great project that I will definitely be making use of.

**Comment by MarkPieszak** [comment]
Glad to hear it ! 💯 
Best of luck, if anything comes up let me know.
